// layouts related
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const OPEN_SIDE_NAV = "OPEN_SIDE_NAV";
export const CLOSE_SIDE_NAV = "CLOSE_SIDE_NAV";

// Requests related
export const GET_JOIN_REQUESTS = "GET_JOIN_REQUESTS";
export const GET_POST_REQUESTS = "GET_POST_REQUESTS";
export const POST_REQUESTS_ERROR = "POST_REQUESTS_ERROR";
export const JOIN_REQUESTS_ERROR = "JOIN_REQUESTS_ERROR";
export const APPROVE_POST_REQUEST = "APPROVE_POST_REQUEST";
export const APPROVE_POST_REQUEST_ERROR = "APPROVE_POST_REQUEST_ERROR";
export const APPROVE_JOIN_REQUEST = "APPROVE_JOIN_REQUEST";
export const APPROVE_JOIN_REQUEST_ERROR = "APPROVE_JOIN_REQUEST_ERROR";
export const REJECT_JOIN_REQUEST = "REJECT_JOIN_REQUEST";
export const REJECT_JOIN_REQUEST_ERROR = "REJECT_JOIN_REQUEST_ERROR";
export const REJECT_POST_REQUEST = "REJECT_POST_REQUEST";
export const REJECT_POST_REQUEST_ERROR = "REJECT_POST_REQUEST_ERROR";
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_JOIN_REQUEST = "CREATE_JOIN_REQUEST";

// extras related
export const SUBMIT_ACHIEVEMENT = "SUBMIT_ACHIEVEMENT";
export const ACHIEVEMENT_ERROR = "ACHIEVEMENT_ERROR";
export const GET_ACHIEVEMENTS = "GET_ACHIEVEMENTS";
export const FEEDBACK_ERROR = "FEEDBACK_ERROR";
export const GET_FEEDBACKS = "GET_FEEDBACKS";
export const DELETE_ACHIEVEMENT = "DELETE_ACHIEVEMENT";
export const DELETE_FEEDBACK = "DELETE_FEEDBACK";
export const EXPORT_ACHIEVEMENT = "EXPORT_ACHIEVEMENT";
export const DELETE_ALL_ACHIVEMENTS = "DELETE_ALL_ACHIVEMENTS";
export const DELETE_ALL_FEEDBACKS = "DELETE_ALL_FEEDBACKS";
export const GET_CHANNELS = "GET_CHANNELS";
export const CREATE_CHANNEL = "CREATE_CHANNEL";
export const CHANNELS_ERROR = "CHANNELS_ERROR";

// posts related
export const TOGGLE_LIKE = "TOGGLE_LIKE";
export const TOGGLE_DISLIKE = "TOGGLE_DISLIKE";
export const LIKE_ERROR = "LIKE_ERROR";
export const DISLIKE_ERROR = "DISLIKE_ERROR";
export const DELETE_POST = "DELETE_POST";
export const CREATE_POST = "CREATE_POST";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const ADD_COMMENT = "ADD_COMMENT";
export const POST_ERROR = "POST_ERROR";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const CLEAR_POSTS = "CLEAR_POSTS";
export const CLEAR_REQUESTS = "CLEAR_REQUESTS";
export const SET_POST_SETTING = "SET_POST_SETTING";
export const GET_POST_SETTING = "GET_POST_SETTING";

//users related
export const GET_USER = "GET_USER";
export const GET_USERS = "GET_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const CLEAR_USER = "CLEAR_USER";
export const CLEAR_USERS = "CLEAR_USERS";
export const USER_ERROR = "USER_ERROR";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const MAKE_ADMIN = "MAKE_ADMIN";
export const MAKE_ADMIN_ERROR = "MAKE_ADMIN_ERROR";
export const GET_REPOS = "GET_REPOS";
export const REMOVE_ADMIN = "REMOVE_ADMIN";
export const REMOVE_ADMIN_ERROR = "REMOVE_ADMIN_ERROR";
export const BLOCK_USER = "BLOCK_USER";
export const BLOCK_USER_ERROR = "BLOCK_USER_ERROR";
export const UNBLOCK_USER = "UNBLOCK_USER";
export const UNBLOCK_USER_ERROR = "UNBLOCK_USER_ERROR";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";

// auth related
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";


// chat related
export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const GET_MESSAGES = "GET_MESSAGES";
export const MESSAGE_SENT = "MESSAGE_SENT";
